Added subtitles accessibility for Lookmovie
JamesHawkinss/movie-web pull request #29
Opened 2021-09-13 18:39 UTC by mansoor-roeen-glitch

Made a few changes to VideoElement.js, Movie.js, Lookmovie.js, Search.js, and UseMovie.js.

2021-09-13 19:06 UTC, JamesHawkinss requested changes
It may also be beneficial to add a small icon on the MovieRow component for lookmovie results that shows that captions are available.

Good work so far.

2021-09-13 19:06 UTC, JamesHawkinss commented on src/hooks/useMovie.js
> +                setStreamData(p => {
Why?

2021-09-13 19:06 UTC, JamesHawkinss commented on src/lib/scraper/lookmovie.js
> +    const accessInfo = await getAccessToken(config);
You can destructure the accessInfo array here:

`const { token, subtitles } = await getAccessToken(config);`

2021-09-13 19:06 UTC, JamesHawkinss commented on src/lib/scraper/lookmovie.js
> +
Remove extra new line after function definition

2021-09-13 19:06 UTC, JamesHawkinss commented on src/views/Search.js
> +                subtitles: subtitles
No need to double up here, just put `subtitles`

2021-09-13 19:09 UTC, JoshHeng requested changes
Looks good, just a few formatting changes.
Please also add new domain to `worker.js` `allowedDomains`

2021-09-13 19:09 UTC, JoshHeng commented on src/lib/scraper/lookmovie.js
> +    const accessInfo = await getAccessToken(config);
Change to:

```js
const { subtitles, token: accessToken } = await getAccessToken(config);
```

2021-09-13 19:09 UTC, JoshHeng commented on src/lib/scraper/lookmovie.js
> +    return {videoUrl: videoUrl.startsWith("/") ? `${BASE_URL}${videoUrl}` : videoUrl, subs};
Change formatting:
```js
return {
    videoUrl: videoUrl.startsWith("/") ? `${BASE_URL}${videoUrl}` : videoUrl,
    subs,
};
```

2021-09-13 19:09 UTC, JoshHeng commented on src/lib/scraper/lookmovie.js
> +
Random tab?

2021-09-13 19:09 UTC, JoshHeng commented on src/views/Search.js
> +                subtitles: subtitles
Just need to put `subtitles`, not `subtitles: subtitles`

2021-09-13 19:09 UTC, JoshHeng commented on src/lib/scraper/lookmovie.js
> +    let subtitles = data?.data?.subtitles;
Use `const`

2021-09-13 19:09 UTC, JoshHeng commented on src/lib/scraper/lookmovie.js
> +    if (token) return {token, subtitles};
Add spaces in object, i.e. `{ token, subtitles }`

2021-09-13 19:09 UTC, JoshHeng commented on src/lib/scraper/lookmovie.js
>  async function getAccessToken(config) {
Function should be renamed to `getAccessInfo`

2021-09-13 19:09 UTC, JoshHeng commented on src/lib/scraper/lookmovie.js
> +        subs = await getEpisodeSubs(config)
Add semicolon

2021-09-13 19:09 UTC, JoshHeng commented on src/lib/scraper/lookmovie.js
> +        subs = subtitles
Add semicolon

2021-09-13 19:09 UTC, JoshHeng commented on src/lib/scraper/lookmovie.js
> +    if (config.type === "show") {
It could be worth just replacing `subtitles` if the config type is `show` rather than creating a new variable - but up to you

2021-09-13 19:11 UTC, JoshHeng commented
Contributes towards #2

2021-09-13 19:57 UTC, mansoor-roeen-glitch commented on src/hooks/useMovie.js
> +                setStreamData(p => {
I was console logging "p" to see what the data was but then forgot to fix it back

2021-09-14 14:49 UTC, JamesHawkinss commented
@mansoor-roeen-glitch text wrapping issue with longer titles. Example: https://sxu.squeezebox.dev/eb8a4/HIFAWOtI98.png/raw

2021-09-15 07:06 UTC, mansoor-roeen-glitch commented
Text wrapping issues have been solved, changes made to MovieRaw.js and MovieRaw.css, waiting for review

2021-09-15 08:12 UTC, JamesHawkinss approved these changes

2021-09-15 08:13 UTC, merged