Add xemovie provider for movies
JamesHawkinss/movie-web pull request #74
Opened 2022-05-02 16:34 UTC by JamesHawkinss

2022-05-02 17:58 UTC, mrjvs requested changes

2022-05-02 17:58 UTC, mrjvs commented on src/providers/list/xemovie/index.ts
> +          ); // do this so no need for CORS errors
how about just putting the proxies url in the subtitle track?

2022-05-02 17:58 UTC, mrjvs commented on src/providers/list/xemovie/index.ts
> +            // eslint-disable-next-line no-await-in-loop
just change the eslint config to disable the rule. I think its fine to have it permanently disabled

2022-05-02 17:58 UTC, mrjvs commented on src/providers/list/xemovie/index.ts
> +      // eslint-disable-next-line no-continue
just change the eslint config to disable the rule. I think its fine to have it permanently disabled

2022-05-02 17:58 UTC, mrjvs commented on src/providers/list/xemovie/index.ts
> +      // eslint-disable-next-line consistent-return
just change the eslint config to disable the rule. I think its fine to have it permanently disabled

2022-05-02 18:12 UTC, JamesHawkinss commented on src/providers/list/xemovie/index.ts
> +          ); // do this so no need for CORS errors
this isn't possible unfortunately

2022-05-02 18:28 UTC, lem6ns commented on src/providers/list/xemovie/index.ts
> +          ); // do this so no need for CORS errors
yep, it isn't possible due to subtitles being very special and needing to be same-origin

2022-05-03 00:02 UTC, mrjvs approved these changes

2022-05-03 12:52 UTC, merged